# Part 2. Vector and Matrix

In this lab, we will learn how to use Python to operate vectors and matrices.

## 1. Example

### 1.1 Load data with pandas

In [ ]:
from google.colab import drive
drive.mount('/content/drive')



Mounted at /content/drive


In [ ]:
from google.colab import files
uploaded = files.upload()

Saving cars.csv to cars.csv


In [ ]:
import numpy as np
import pandas as pd

# load data with pandas
df = pd.read_csv('cars.csv')
# print(df)

# convert a pandas dataframe to a numpy array
X = df.values[:, 1:-1]
print(type(X))
print(X.shape)
print(X)

<class 'numpy.ndarray'>
(406, 7)
[[18.0 8 307.0 ... 3504 12.0 70]
 [15.0 8 350.0 ... 3693 11.5 70]
 [18.0 8 318.0 ... 3436 11.0 70]
 ...
 [32.0 4 135.0 ... 2295 11.6 82]
 [28.0 4 120.0 ... 2625 18.6 82]
 [31.0 4 119.0 ... 2720 19.4 82]]


### 1.2 Operation for vector

In [ ]:
#Get first row and the second to last row

x1 = X[0, :]
x2 = X[-2, :]

print(x1)
print(x2)

# Addition

y = x1 + x2
print(y)

[18.0 8 307.0 130 3504 12.0 70]
[28.0 4 120.0 79 2625 18.6 82]
[46.0 12 427.0 209 6129 30.6 152]


### 1.3 Operation for matrix

In [ ]:
# Get first 5 rows and last 5 rows

m1 = X[0:5, :]
m2 = X[-5:, :]

print(m1)
print(m2)

# Subtraction
m = m1 - m2
print(m)

[[18.0 8 307.0 130 3504 12.0 70]
 [15.0 8 350.0 165 3693 11.5 70]
 [18.0 8 318.0 150 3436 11.0 70]
 [16.0 8 304.0 150 3433 12.0 70]
 [17.0 8 302.0 140 3449 10.5 70]]
[[27.0 4 140.0 86 2790 15.6 82]
 [44.0 4 97.0 52 2130 24.6 82]
 [32.0 4 135.0 84 2295 11.6 82]
 [28.0 4 120.0 79 2625 18.6 82]
 [31.0 4 119.0 82 2720 19.4 82]]
[[-9.0 4 167.0 44 714 -3.5999999999999996 -12]
 [-29.0 4 253.0 113 1563 -13.100000000000001 -12]
 [-14.0 4 183.0 66 1141 -0.5999999999999996 -12]
 [-12.0 4 184.0 71 808 -6.600000000000001 -12]
 [-14.0 4 183.0 58 729 -8.899999999999999 -12]]


## 2 Task

### 2.1 Get the first column and the second to last column from X

In [ ]:
# this is your code to get two

#first column
y1 = X[: , 1]

#second to last column
y2 = X[: ,-2]

print(y1)
print(y2)

[8 8 8 8 8 8 8 8 8 8 4 8 8 8 8 8 8 8 8 8 4 6 6 6 4 4 4 4 4 4 6 8 8 8 8 4 4
 4 4 4 6 6 6 6 6 8 8 8 8 8 8 8 6 4 6 6 4 4 4 4 4 4 4 4 4 4 4 4 4 8 8 8 8 8
 8 8 8 8 3 8 8 8 8 4 4 4 4 4 4 4 4 4 8 8 8 8 8 8 8 8 8 8 8 8 6 6 6 6 6 4 8
 8 8 8 6 4 4 4 3 4 6 4 8 8 4 4 4 4 8 4 6 8 6 6 6 6 4 4 4 4 6 6 6 8 8 8 8 8
 4 4 4 4 4 4 4 4 4 4 4 6 6 6 6 8 8 8 8 6 6 6 6 6 8 8 4 4 6 4 4 4 4 6 4 6 4
 4 4 4 4 4 4 4 4 4 8 8 8 8 6 6 6 6 4 4 4 4 6 6 6 6 4 4 4 4 4 8 4 6 6 8 8 8
 8 4 4 4 4 4 8 8 8 8 6 6 6 6 8 8 8 8 4 4 4 4 4 4 4 4 6 4 3 4 4 4 4 4 8 8 8
 6 6 6 4 6 6 6 6 6 6 8 6 8 8 4 4 4 4 4 4 4 4 5 6 4 6 4 4 6 6 4 6 6 8 8 8 8
 8 8 8 8 4 4 4 4 5 8 4 8 4 4 4 4 4 6 6 4 4 4 4 4 4 4 4 6 4 4 4 4 4 4 4 4 4
 4 5 4 4 4 4 4 6 3 4 4 4 4 4 4 6 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 6 6
 6 6 8 6 6 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 6 6 4 6 4 4 4 4 4 4 4 4]
[12.0 11.5 11.0 12.0 10.5 10.0 9.0 8.5 10.0 8.5 17.5 11.5 11.0 10.5 11.0
 10.0 8.0 8.0 9.5 10.0 15.0 15.5 15.5 16.0 14.5 20.5 17.5 14.5 17.5 12.5
 15.0 14.0 15.0 13.5 18.5 14.5

### 2.2 Perform following operations on these two vectors and print the result

In [ ]:

# 1. addition and subtraction

add = y1 + y2
print(add)

sub = y1 - y2
print(sub)

# 2. element-wise multiplication

mult = y1 * y2
print(mult)

# 3. inner product
inner_prod = np.inner(y1,y2)
print(inner_prod)
# 4. three norms



# 5. compute the distance between these two vectors

dist = np.linalg.norm(y1-y2, ord = 2)
print(dist)


[20.0 19.5 19.0 20.0 18.5 18.0 17.0 16.5 18.0 16.5 21.5 19.5 19.0 18.5
 19.0 18.0 16.0 16.0 17.5 18.0 19.0 21.5 21.5 22.0 18.5 24.5 21.5 18.5
 21.5 16.5 21.0 22.0 23.0 21.5 26.5 18.5 19.5 18.0 23.0 24.0 19.0 21.5
 21.5 21.5 21.5 20.0 19.5 21.5 21.0 19.5 20.0 20.0 19.5 23.0 21.0 20.5
 18.0 18.0 23.5 18.5 23.0 22.0 23.0 24.5 19.5 21.0 27.5 23.5 20.5 20.0
 20.0 21.5 21.0 19.5 19.0 21.5 21.5 20.5 16.5 20.5 22.0 24.0 22.0 18.5
 22.0 23.5 22.0 20.0 21.0 18.5 19.0 20.5 21.0 19.5 21.0 22.5 20.5 19.5
 20.0 21.0 22.5 19.0 19.0 19.0 22.5 24.0 22.0 22.5 22.0 25.0 22.0 20.5
 21.0 20.5 21.0 23.0 23.5 20.5 16.5 22.5 20.0 19.5 21.0 17.5 23.5 19.5
 18.0 19.5 19.0 18.0 19.5 19.0 22.5 23.0 22.0 23.0 23.0 20.5 25.0 21.0
 23.0 24.0 22.5 22.0 22.5 21.5 24.0 23.5 20.5 19.5 18.5 20.5 23.0 18.5
 19.5 18.0 19.0 19.5 20.0 22.0 22.0 27.0 25.5 19.5 22.0 22.5 21.5 27.0
 24.5 25.0 25.0 21.0 21.5 20.0 20.0 21.0 22.0 22.5 17.5 20.5 21.0 20.5
 18.0 23.0 19.0 21.0 18.5 17.5 21.5 19.5 20.9 18.9 21.7 19.3 21.0 21.0
 21.9 

### 2.3 Get the first three columns and the last three columns from X

In [ ]:
# this is your code to get two matrices: A, B

A = X[:,0:3]
B = X[:, -3:]

print(A)
print(B)

[[18.0 8 307.0]
 [15.0 8 350.0]
 [18.0 8 318.0]
 ...
 [32.0 4 135.0]
 [28.0 4 120.0]
 [31.0 4 119.0]]
[[3504 12.0 70]
 [3693 11.5 70]
 [3436 11.0 70]
 ...
 [2295 11.6 82]
 [2625 18.6 82]
 [2720 19.4 82]]


### 2.4 Perform following operations on these two matrices and print the result

In [ ]:

A = X[:,0:3]
B = X[:, -3:]

# 1. addition and subtraction
add = A + B
print(add)


# 2. compute the transpose of the second matrix: C = B^T, and print the shape of C
C = np.transpose(B)
print(C.shape)

# 3. compute the product between A and C, and print the result and its shape
prod = np.dot(A, C)
print(prod.shape)


# 4. compute the transpose of the first matrix: D = A^T, and print the shape of D
D = np.transpose(A)
D.shape
# 5. compute the product between D and B, and print the result and its shape
prod = np.dot(D, B)
print(prod)

[[3522.0 20.0 377.0]
 [3708.0 19.5 420.0]
 [3454.0 19.0 388.0]
 ...
 [2327.0 15.6 217.0]
 [2653.0 22.6 202.0]
 [2751.0 23.4 201.0]]
(3, 406)
(406, 406)
[[25614040.900000002 149295.04000000004 718009.0999999995]
 [7149030 33484.69999999997 167835]
 [269175402.0 1160836.2999999998 5943079.0]]
